config/routes.rb
Rails.application.routes.draw do
  resources :book_reviews
  get 'users/show'
  get 'static_pages/home'
  devise_for :users
  resources :books
  root "static_pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/book.rb
class Book < ApplicationRecord
    has_one_attached :image
    has_many :book_review, ->{ order('created_at DESC') }, :class_name => 'BookReview'
    belongs_to :user, :optional => true
end

app/models/book_review.rb
class BookReview < ApplicationRecord
    belongs_to :user
    belongs_to :book
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         has_one_attached :avatar

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected
    def configure_permitted_parameters
     devise_parameter_sanitizer.permit :sign_up, keys: [:name, :age, :avatar]
     devise_parameter_sanitizer.permit :account_update, keys: [:name, :age, :avatar]
    end    
end

app/controllers/book_reviews_controller.rb
class BookReviewsController < ApplicationController
  before_action :set_book_review, only: %i[ show edit update destroy ]

  # GET /book_reviews or /book_reviews.json
  def index
    @book_reviews = BookReview.all
  end

  # GET /book_reviews/1 or /book_reviews/1.json
  def show
  end

  # GET /book_reviews/new
  def new
    @book_review = BookReview.new
  end

  # GET /book_reviews/1/edit
  def edit
  end

  # POST /book_reviews or /book_reviews.json
  def create
    @book_review = BookReview.new(book_review_params)
    url = "/books/#{@book_review.book_id.to_s}"

    respond_to do |format|
      if @book_review.save
        format.html { redirect_to url, notice: "Book review was successfully created." }
        format.json { render :show, status: :created, location: @book_review }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @book_review.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /book_reviews/1 or /book_reviews/1.json
  def update
    respond_to do |format|
      if @book_review.update(book_review_params)
        format.html { redirect_to book_review_url(@book_review), notice: "Book review was successfully updated." }
        format.json { render :show, status: :ok, location: @book_review }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @book_review.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /book_reviews/1 or /book_reviews/1.json
  def destroy
    @book_review.destroy

    respond_to do |format|
      format.html { redirect_to book_reviews_url, notice: "Book review was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book_review
      @book_review = BookReview.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def book_review_params
      params.require(:book_review).permit(:user_id, :book_id, :review)
    end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: %i[ show edit update destroy ]
  before_action :authenticate_user!


  # GET /books or /books.json
  def index
    @books = Book.all
  end

  # GET /books/1 or /books/1.json
  def show
    @book_review = BookReview.new
  end

  # GET /books/new
  def new
    @book = Book.new
  end

  # GET /books/1/edit
  def edit
  end

  # POST /books or /books.json
  def create
    @book = Book.new(book_params)

    respond_to do |format|
      if @book.save
        format.html { redirect_to book_url(@book), notice: "Book was successfully created." }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1 or /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to book_url(@book), notice: "Book was successfully updated." }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1 or /books/1.json
  def destroy
    @book.destroy

    respond_to do |format|
      format.html { redirect_to books_url, notice: "Book was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def book_params
      params.require(:book).permit(:title, :number_of_pages, :image, :detail)
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  before_action :authenticate_user!
  def home
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_reviews_helper.rb
module BookReviewsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/book_reviews/_book_review.html.erb
<div id="<%= dom_id book_review %>">
  <p>
    <strong>User:</strong>
    <%= book_review.user_id %>
  </p>

  <p>
    <strong>Book:</strong>
    <%= book_review.book_id %>
  </p>

  <p>
    <strong>Review:</strong>
    <%= book_review.review %>
  </p>

</div>

app/views/book_reviews/_form.html.erb
<%= form_with(model: book_review) do |form| %>
  <% if book_review.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(book_review.errors.count, "error") %> prohibited this book_review from being saved:</h2>

      <ul>
        <% book_review.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :user_id, style: "display: block" %>
    <%= form.number_field :user_id %>
  </div>

  <div>
    <%= form.label :book_id, style: "display: block" %>
    <%= form.number_field :book_id %>
  </div>

  <div>
    <%= form.label :review, style: "display: block" %>
    <%= form.text_area :review %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/book_reviews/edit.html.erb
<h1>Editing book review</h1>

<%= render "form", book_review: @book_review %>

<br>

<div>
  <%= link_to "Show this book review", @book_review %> |
  <%= link_to "Back to book reviews", book_reviews_path %>
</div>

app/views/book_reviews/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Book reviews</h1>

<div id="book_reviews">
  <% @book_reviews.each do |book_review| %>
    <%= render book_review %>
    <p>
      <%= link_to "Show this book review", book_review %>
    </p>
  <% end %>
</div>

<%= link_to "New book review", new_book_review_path %>

app/views/book_reviews/new.html.erb
<h1>New book review</h1>

<%= render "form", book_review: @book_review %>

<br>

<div>
  <%= link_to "Back to book reviews", book_reviews_path %>
</div>

app/views/book_reviews/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @book_review %>

<div>
  <%= link_to "Edit this book review", edit_book_review_path(@book_review) %> |
  <%= link_to "Back to book reviews", book_reviews_path %>

  <%= button_to "Destroy this book review", @book_review, method: :delete %>
</div>

app/views/books/_book.html.erb
<div id="<%= dom_id book %>">
  <h5>
    <strong>Title:</strong>
    <%= book.title %>
  </h5>

  <h5>
    <strong>Number of pages:</strong>
    <%= book.number_of_pages %>
  </h5>

</div>

app/views/books/_form.html.erb
<%= form_with(model: book) do |form| %>
  <% if book.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
        <% book.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :number_of_pages, style: "display: block" %>
    <%= form.number_field :number_of_pages %>
  </div>
  <div class="field">
    <%= form.label :image %>
    <%= form.file_field :image %><br>
  </div>
  <div class="field">
    <%= form.label :detail %>
    <%= form.text_area :detail %>
  </div>
  <div> 
    <%= form.submit%>
  </div>
<% end %>

app/views/books/edit.html.erb
<h1>Editing book</h1>

<%= render "form", book: @book %>

<br>

<div>
  <%= link_to "Show this book", @book, class: "btn btn-success"  %>
  <%= link_to "Back to books", books_path, class: "btn btn-primary" %>
</div>

app/views/books/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Books</h1>

<table class="table table-bordered">
  <thead>
    <tr>
      <th>Title</th>
      <th>Number of pages</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @books.each do |book| %>
      <tr>
        <td><%= book.title %></td>
        <td><%= book.number_of_pages %></td>
        <td><%= link_to 'Show', book %></td>
        <td><%= link_to 'Edit', edit_book_path(book) %></td>
        <td><%= link_to 'Destroy', book, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Book', new_book_path, class: "btn btn-success" %>

app/views/books/new.html.erb
<h1>New book</h1>

<%= render "form", book: @book %>

<br>

<div>
  <%= link_to "Back to books", books_path, class: "btn btn-primary" %>
</div>

app/views/books/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @book %>

<p>
   <% if @book.image.attached? %>
     <%= image_tag @book.image, size: 500 %>
   <% end %>
</p>

 <h5>
  <strong>Details:</strong>
  <%= @book.detail %>
</h5>

<%= form_with(model: @book_review) do |form| %>
  <h2>Review Form</h2>
  <div>
    <%= form.label :review, style: "display: block" %>
    <%= form.text_area :review %>
    <%= form.hidden_field :user_id, :value => current_user.id %>
    <%= form.hidden_field :book_id, :value => @book.id %>
  </div>
  <div class="actions">
    <%= form.submit %>
  </div>
    <% end %>

<h2>Review list</h2>
  <ul>
    <% @book.book_review.each do |book_review| %>
      <li><%= book_review.review %> (<i><%= book_review.user.name %></i>)</li>
    <% end %>
</ul>
<div>
  <%= link_to "Edit this book", edit_book_path(@book), class: "btn btn-success" %>
  <%= link_to "Back to books", books_path, class:"btn btn-primary"  %>

  <%= button_to "Destroy this book", @book, method: :delete, class:"btn btn-danger" %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Books App</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <%= link_to 'Home', root_path, class:"navbar-brand align-top"%>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to "Books", books_path, class: "nav-link active"%>
        </li>
            <li class="nav-item">
            <%= link_to "Log Out", destroy_user_session_path, method: :delete,class: "nav-link active"%>
        </li>
        <li class="nav-item">
            <%= link_to "Edit Profile", edit_user_registration_path,class: "nav-link active"%>
        </li>
        <% else %>
        <li class="nav-item">
            <%= link_to "Sign Up", new_user_registration_path, class: "nav-link active"%>
        </li>
        <li class="nav-item">
            <%= link_to "Log In", new_user_session_path, class: "nav-link active"%>
        </li>
          <% end %>>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Dropdown
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><%= link_to "Edit Profile", edit_user_registration_path,class: "nav-link active"%>Edit profile</a></li>
            <li><a class="dropdown-item" href="#">Another action</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#">Something else here</a></li>
          </ul>
        </li>
      </ul>
</div>
</div>
</nav>

    <%= yield %>
  </body>
</html>

app/views/static_pages/home.html.erb
<div class="content">
<h1>こんにちは, <%= current_user.name%></h1>
</div>

<style>
.content {
  max-width: 500px;
  margin: auto;
}
</style>

app/views/users/show.html.erb
<p>
  <% if current_user.avatar.attached? %>
    <%= image_tag current_user.avatar %>
  <% end %>
</p>

<h3>名前</h3>
<%= current_user.name %>

<h3>年齢</h3>
<%= current_user.age %>

<h3>メールアドレス</h3>
<%= current_user.email %> 